### ISSUE TITLE
Zip extraction failed fully or partially.

### ISSUE THREAD

**Issue by Noenko** [FenPhoenix/AngelLoader#80]
Angel Loader won't work with any version besides 1.4.8. or lower, I removed any old files from previous Angel Loader versions. Here's some info on my problems.

I am using version 1.5.1

I get no readme info, and I can't install FM's.

My Log:

2021/5/16` 14:43:35 1.5.1 Started session

2021/5/16 14:43:37 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:43:39 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:43:40 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:43:42 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:43:43 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:44:30 ZipExtract
Exception in zip extract to cache
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMCache.ZipExtract(String fmArchivePath, String fmCachePath, List`1 readmes)

2021/5/16 14:44:32 InstallFMZip
Exception while installing zip C:\Users\Hidden\Desktop\Thief Games\FMs\Gems_of_Provenance.zip to C:\Users\Hidden\Desktop\Thief Games\Thief Gold\FMs\Gems_of_Provenance
EXCEPTION:
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at AngelLoader.FMInstallAndPlay.InstallFMZip(String fmArchivePath, String fmInstalledPath)

**Comment by FenPhoenix** [comment]
Okay, this is an issue with a fix for filename character encoding when extracting zip files. It's supposed to be using your operating system's default character encoding (this is standard behavior for zip extractors), but it's getting a weird/wrong result. There's no such thing as "code page 1" afaik so I dunno what's going on there, but I'll have to write a fallback.

**Comment by FenPhoenix** [comment]
Try this new test version: https://fenphoenix.com/apps/AngelLoader/test_versions/AngelLoader_v1.5.1%20codepage%20fallback%20test1.zip

**Comment by Noenko** [comment]
Now everything works as it should! Thanks for the quick help. :D

**Comment by FenPhoenix** [comment]
Okay, I'll prepare an official bugfixed release. Thanks for the report :)
